# Generated by Django 5.0.6 on 2024-11-25 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sport", "0002_populate_sports"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(upload_to="images/sport_posts/"),
        ),
        migrations.AlterField(
            model_name="team",
            name="image",
            field=models.ImageField(upload_to="images/team_image/"),
        ),
    ]
