# Generated by Django 5.0.6 on 2024-07-26 18:04

from django.db import migrations


def populate_court_data(apps, schema_editor):
    Court = apps.get_model("reservation", "Court")

    Court.objects.bulk_create(
        [
            Court(label="Tennis Court"),
            Court(label="Basketball Court"),
            Court(label="Baseball Field"),
            Court(label="Soccer Field"),
            Court(label="Volleyball Court"),
            Court(label="Badminton Court"),
            Court(label="Hockey Rink"),
            Court(label="Cricket Ground"),
            Court(label="Rugby Field"),
            Court(label="Golf Course"),
        ]
    )


def reverse_func(apps, schema_editor):
    Court = apps.get_model("reservation", "Court")
    Court.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("reservation", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(
            populate_court_data,
            reverse_func,
        ),
    ]
