# Generated by Django 4.2.13 on 2025-01-12 14:52

from django.db import migrations , models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
            migrations.CreateModel(
                name='Equipment',
                fields=[
                    ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                    ('item', models.CharField(max_length=100)),
                    ('sport', models.IntegerField()),
                    ('count', models.IntegerField(default=0)),
                ],
            ),
        ]
