# Generated by Django 5.0.6 on 2024-07-26 17:32

from django.db import migrations


def populate_usertype(apps, schema_editor):
    UserType = apps.get_model("userProfile", "UserType")

    UserType.objects.bulk_create(
        [
            UserType(name="student"),
            UserType(name="academic"),
            UserType(name="postgraduate"),
            UserType(name="external"),
            UserType(name="internal"),
            UserType(name="approval"),
            UserType(name="payment"),
            UserType(name="staff"),
            UserType(name="admin"),
        ]
    )


def reverse_populate_usertype(apps, schema_editor):
    UserType = apps.get_model("userProfile", "UserType")
    UserType.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("userProfile", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(
            populate_usertype,
            reverse_populate_usertype,
        ),
    ]
