# Generated by Django 5.0.6 on 2024-07-26 17:39

from django.db import migrations


def create_faculty_data(apps, schema_editor):
    Faculty = apps.get_model("userProfile", "Faculty")  # Replace 'your_app_name'
    Faculty.objects.bulk_create(
        [
            Faculty(name="Science", code="sci"),
            Faculty(name="Engineering", code="eng"),
            Faculty(name="Arts", code="arts"),
            Faculty(name="Medicine", code="med"),
            Faculty(name="Management", code="mgt"),
            Faculty(name="Veterinary Medicine and Animal Science", code="vet"),
            Faculty(name="Dental Sciences", code="dental"),
            Faculty(name="Agriculture", code="agri"),
            Faculty(name="Allied Health Science", code="ahs"),
        ]
    )


def delete_faculty_data(apps, schema_editor):
    Faculty = apps.get_model("userProfile", "Faculty")
    Faculty.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("userProfile", "0005_populate_groups"),
    ]

    operations = [
        migrations.RunPython(create_faculty_data, delete_faculty_data),
    ]
