# Generated by Django 5.0.6 on 2025-01-22 16:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("userProfile", "0006_populate_faculties"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Family",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FamilyMembers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("nic", models.CharField(max_length=20)),
                ("relationship", models.CharField(max_length=20)),
                ("age", models.IntegerField()),
                (
                    "family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="member.family"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Members",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("age", models.IntegerField()),
                ("household", models.CharField(max_length=100)),
                ("formType", models.CharField(max_length=100)),
                ("membership", models.CharField(max_length=50)),
                ("residence", models.CharField(max_length=100)),
                ("price", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "userProfile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="userProfile.userprofile",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="family",
            name="members",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="member.members"
            ),
        ),
        migrations.CreateModel(
            name="AcademicStaffMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("designation", models.CharField(max_length=50)),
                ("temporary", models.CharField(max_length=10)),
                (
                    "members",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="member.members"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OutsidersMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "members",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="member.members"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PostgraduateMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pg_name", models.CharField(max_length=100)),
                ("stu_reg_no", models.CharField(max_length=50)),
                (
                    "members",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="member.members"
                    ),
                ),
            ],
        ),
    ]
