# Generated by Django 5.0.6 on 2025-01-14 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
        ('userProfile', '0006_populate_faculties'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='userProfile',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='userProfile.userprofile'),
            preserve_default=False,
        ),
    ]
