# Generated by Django 4.2.13 on 2025-01-20 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('registration_number', models.CharField(max_length=50, unique=True)),
                ('phone_number', models.CharField(max_length=10)),
                ('faculty', models.CharField(max_length=100)),
                ('sports_experiences', models.TextField(blank=True, null=True)),
                ('achievements', models.JSONField(default=list)),
            ],
        ),
    ]
