# Generated by Django 5.0.6 on 2025-01-21 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("registration_number", models.CharField(max_length=50, unique=True)),
                ("phone_number", models.CharField(max_length=10)),
                ("faculty", models.CharField(max_length=100)),
                ("sports_experiences", models.TextField()),
                ("achievements", models.JSONField()),
            ],
        ),
    ]
