# Generated by Django 5.0.6 on 2025-01-23 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studentData", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="achievements",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="student",
            name="sports_experiences",
            field=models.TextField(blank=True, null=True),
        ),
    ]
